version: 2
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    dir: ./cmd/skm
    goos:
      - linux
      - windows
      - darwin
      - freebsd
      - openbsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
      - mips
      - mipsle
      - mips64
      - mips64le
    ldflags:
      - -s -w -X main.Version={{.Tag}}
archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md
      - completions/skm.bash
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
